name: fuel_pro_360
description: "Fuel Pro 360"

publish_to: "none"

version: 1.0.15+16

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0

  # translation
  intl: ^0.19.0

  # routing
  go_router: ^14.3.0

  # state management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # network
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  cached_network_image: ^3.4.1
  signalr_netcore: ^1.4.0

  # local storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Utils
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  flutter_native_splash: ^2.4.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  internet_connection_checker_plus: ^2.5.2
  dropdown_button2: ^2.3.9

  supabase_flutter: ^2.9.1

  #image
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # code generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4
  riverpod_generator: ^2.6.2

  # Utils
  import_sorter: ^4.6.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
